Fix23
EarthSciML/Aerosol.jl pull request #27
Opened 2024-03-29 06:26 UTC by jialinl6

Fixes #23

2024-04-01 15:01 UTC, ctessum requested changes
Thanks! Just a couple of suggestions above. Also it would be good if you can add a documentation page that describes the algorithm and demonstrates how to use it, for example including the analysis in Kai's spreadsheet that reproduces the figure in the original paper.

2024-04-01 15:01 UTC, ctessum requested changes
Thanks! Just a couple of suggestions above. Also it would be good if you can add a documentation page that describes the algorithm and demonstrates how to use it, for example including the analysis in Kai's spreadsheet that reproduces the figure in the original paper.

2024-04-01 15:11 UTC, ctessum commented
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Monday, 01-Apr-24 15:11:10 UTC` by Gov4Git `dev`

#### Notice `fvs7ij`
Started managing this PR as Gov4Git proposal `27` with initial __approval score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.

2024-04-01 16:24 UTC, jialinl6 commented on src/VBS.jl
> +function VBS(Ci)
Sure, I will do that! I have run the comparison with Kai's spreadsheet that reproduces the figure in the original paper. Since the function format is acceptable, I will add the documentation.

2024-04-01 16:24 UTC, jialinl6 commented on src/VBS.jl
> +function calc_Ci_star(T, Ci_star_standard)
Will do!

2024-04-04 18:59 UTC, jialinl6 commented
The documentation looks like this: [VBS · Aerosol.jl.pdf](https://github.com/EarthSciML/Aerosol.jl/files/14876042/VBS.Aerosol.jl.pdf)

2024-04-05 20:21 UTC, ctessum approved these changes
Thanks!

2024-04-05 20:24 UTC, ctessum commented
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 05-Apr-24 20:24:44 UTC` by Gov4Git `dev`

#### Notice `pdayz2`
This PR's __approval score__ is now `3.000000`.
The __cost of review__ is `9.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `u5i4ul`
The set of eligible issues claimed by this PR is now empty.

2024-04-05 20:30 UTC, merged

2024-04-05 20:38 UTC, ctessum commented
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 05-Apr-24 20:38:34 UTC` by Gov4Git `dev`

#### Notice `dxkvjc`
This PR, managed as Gov4Git proposal `27`, has been closed 🎉

The PR approval tally was `3.000000`.

Bounty of `0.000000` credits was donated to the community's matching fund.

Resolved issues:

Rewarded PR reviewers:
- Reviewer @ctessum was awarded `9.000000` credits

Tally breakdown by user:
- User @ctessum contributed `3.000000` votes